version: '3'
 
networks:
  wordpress:
    driver: bridge
  
services:
 
  wp:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html/
    environment:
      WORDPRESS_DB_PASSWORD : yourpassword
      WORDPRESS_DB_HOST     : db:3306
      WORDPRESS_DB_USER     : wp
      WORDPRESS_DB_NAME     : wp
    networks:
      - wordpress
    restart: always
 
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD   : yourpassword
      MYSQL_PASSWORD        : yourpassword
      MYSQL_USER            : wp
      MYSQL_DATABASE        : wp
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - wordpress
    restart: always
